version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:
      - run:
        name: Chmod permissions
        command: sudo chmod +x ./gradlew
      - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
     
